### PR TITLE
README: Add information about Drake's fork

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This includes a process for merging PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri and +@jamiesnape for review, please?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-:-Ly_Mn8c88ETwsw2MWLW:b-n4hg0k)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jamiesnape and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Good so far.  I'll test out the recipes soon.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-:-LydakDD3YO5CItOJ2dT:bksgqfi)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @jamiesnape)

___
*[README_DRAKE.md, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-Lyd_nF32sepDrKWs1Q3:-Lyd_nF32sepDrKWs1Q4:bq5jniz) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L23)):*
> ```Markdown
> * [User: Python Bindings](https://drake.mit.edu/python_bindings.html#using-the-python-bindings)
> * [Dev: Python Bindings](https://drake.mit.edu/doxygen_cxx/group__python__bindings.html)
> * [User: API Reference](https://drake.mit.edu/pydrake/index.html#://)
> ```

nit I don't think we need the duck emoticon (`#://`) at the end here?
___
*[README_DRAKE.md, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydabWe6Dfvuz5gydt1:-LydabWe6Dfvuz5gydt2:b-942tnx) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L60)):*
> ```Markdown
> Windows testing (with AppVeyor) is disabled for this repository.
> 
> ## Local Git Setup
> ```

Somewhere in this README, I'd like to see a description of any branches and tags that exist on RobotLocomotion/pybind11 that are not already mentioned in the document.

(This would be easier if we purge all of the vestigial branches and tags that have no more reason to exist.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: pending discussions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-:-LydeLFIC34PlAett3Wl:b67tr8b)* status: all files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @jamiesnape)

___
*[README_DRAKE.md, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydbpIk-uS_xd8i6zFn:-LydbpIl4jzIjhx5DU5n:b1aeb2e) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L69)):*
> ```Markdown
>     git clone --origin upstream https://github.com/pybind/pybind11
>     cd pybind11
>     git remote --set-url --push upstream no_push
> ```

nit Just `set-url` not `--set-url`.  Ditto a few lines below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jamiesnape and @jwnimmer-tri)

___
*[README_DRAKE.md, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydabWe6Dfvuz5gydt1:-LyfSGrQ8P-9z7acHsGV:b7rva5h) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Somewhere in this README, I'd like to see a description of any branches and tags that exist on RobotLocomotion/pybind11 that are not already mentioned in the document.

(This would be easier if we purge all of the vestigial branches and tags that have no more reason to exist.)
</blockquote></details>

Done.

I'll go ahead and purge the following branches / tags, unless you object:
`upstream`, `upstream_new`, `last_sha_of_previous_fork` (branch and tag)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jamiesnape and @jwnimmer-tri)

___
*[README_DRAKE.md, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydabWe6Dfvuz5gydt1:-LyfSSzJ6wgSPd7lARO9:bspcs3m) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.

I'll go ahead and purge the following branches / tags, unless you object:
`upstream`, `upstream_new`, `last_sha_of_previous_fork` (branch and tag)
</blockquote></details>

Oh, and `master`. I'll set `drake` to the default branch after this merges.

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

___
*[README_DRAKE.md, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydabWe6Dfvuz5gydt1:-LyfSb44C6htVUMSruz3:b-qsl6o0) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Oh, and `master`. I'll set `drake` to the default branch after this merges.
</blockquote></details>

Fine by me.  (Dunno if you have to consult anyone else?)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

___
*[README_DRAKE.md, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-LydabWe6Dfvuz5gydt1:-LyfW_tQ2_BODqi248Gx:b-gteolh) ([raw file](https://github.com/robotlocomotion/pybind11/blob/a2b1ef4aabb09f20b8d2e262eb1c1dcdc72921d2/README_DRAKE.md#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fine by me.  (Dunno if you have to consult anyone else?)
</blockquote></details>

OK I've already asked Jamie about re-setting some branches, so should be good to go.

**Review by EricCousineau-TRI — COMMENTED** [review]
-@jamiesnape for now, can fix things afterwards

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/36#-:-LyfWfUwD59nLoRkJ9MS:b-mx89rt)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
