### PR TITLE
Merge 'upstream/master' (07e2259) from previous merge-base (12e8774)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Process:
- [x] Submit PR to Drake using this branch. Ensure experimental CI passes (https://github.com/RobotLocomotion/drake/pull/12572)
- [x] Review this PR.
- ~Merge old `drake` into `no_prune` with `merge --no-ff --strategy=ours`~
- ~Reset `last_sha_of_previous_fork` to old `drake`, force push~
- ~Reset `upstream`, push without `--force`~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/34)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review, please?

At a high-level is, this all seems like bug and aesthetic fixes (esp. the import error_already_set part), with one feature on readonly buffers.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/34#-:-LyW1qvxAejYNupuzZdV:bvu0h5)* status: 0 of 35 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Neither https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/pybind11 nor https://github.com/RobotLocomotion/pybind11/tree/master nor https://github.com/RobotLocomotion/pybind11/tree/drake nor any other branch appears to explain the git strategy we use to maintain the fork.

I don't need spoon-fed command lines, but I do need a few sentences about our approach and which branch names and/or tags in our repo are relevant vs strays.  I can settle for a discussion thread in the PR here with that detail, to be merged into a docs tree somewhere later.

Or does it exist already and I overlooked it?

**Comment by jwnimmer-tri** [comment]
(And as far as code review, I don't care about reviewing the diffs at all -- once we have the branch policy and CI checks enumerated, review should be as simple as comparing the PR vs those items.  We don't need to re-review upstream.)

**Comment by BetsyMcPhail** [comment]
Before we update the PyBind version on Drake, #32 needs to be reverted - it causes segfaults on Mac builds. 

I opened #35 to for the revert.

**Comment by EricCousineau-TRI** [comment]
@BetsyMcPhail Thanks! Merged it in.

@jwnimmer-tri It does not exist yet - sorry about that! I will follow-up after this PR and merge in some instructions that are hopefully easy to discover.

We started out with a rebasing Git merge strategy, but I found that to be a bit burdensome. I then switched to a merge strategy, and that seems fine. The checklist outlined above is a modified form of what I've done on prior PRs.

Some notes on branches / tags:
- `master` is not useful. I think it was written to be a deterrent from other people using the fork (with the hopes of de-forking), but that's unlikely to happen. I would like to just update the GitHub page to show `drake`.
- `no_prune` is no longer necessary since we now merge. I just update it out of habit, and to keep prior rebase history alive.
- `last_sha_of_previous_fork` is unfortunately duplicated into a tag and a branch. I will remove the branch and keep the tag. This also could be removed, since we have `no_prune`.
- `upstream` would ideally stay. This just tracks `upstream/master` as `origin/upstream` (a little confusing, admittedly).
- `upstream_new` is junk, I think.

Are you OK with the current merge strategy, with the promise of me cleaning this up afterwards?

**Comment by jwnimmer-tri** [comment]
> Are you OK with the current merge strategy, with the promise of me cleaning this up afterwards?

So #36 is great, thanks.  It should give me enough context to review this PR.

However, the PR description checklist still has these items in it:

> Merge old drake into no_prune with merge --no-ff --strategy=ours
> Reset last_sha_of_previous_fork to old drake, force push

Are they still part of the plan?  They are not listed as steps in #36.

**Comment by jwnimmer-tri** [comment]
:lgtm: review to merge this PR -- (1) the merge commit has the correct parents, (1) the merge commit has correct title, and (3) Drake CI is happy even on macOS.

However, I do not believe that we should do _any_ of the other git items in the top post.

**Comment by EricCousineau-TRI** [comment]
Sounds good to me. Will strike those out.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by EricCousineau-TRI** [comment]
Failure on CI is simply a deadsnakes PPA flake. Going to merge.

**Pull request merged**
