### PR TITLE
Merge 'upstream/master' (70a58c5)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For the author:

- [x] Ensure downstream CI passes (including Mac): RobotLocomotion/drake#16140
  - See results https://github.com/RobotLocomotion/drake/runs/4316508550

For the reviewer: There is no need to review upstream changes in detail. Instead, simply review:

- [x] Does the PR title look correct? (does it only contain up to
`<sha_new>` of upstream?)
- Are the canary builds "correct"?  (look at the [checks](#partial-pull-merging); for each CI configuration, expand the output
under just `Python tests` (which are for C++17) - you should see around 500 tests run and passed)
  - [x] `CI / 🐍 3.6 • ubuntu-latest • x64 [...]`: [base](https://github.com/RobotLocomotion/pybind11/runs/4316004520?check_suite_focus=true) vs. this PR's results for
  `CI / 🐍 3.6 • ubuntu-latest • x64`
  - [x] `CI / 🐍 3.9 • macos-latest • x64`: [base](https://github.com/RobotLocomotion/pybind11/runs/4316004660?check_suite_focus=true) vs. this PR's results for
  `CI / 🐍 3.9 • macos-latest • x64`
- ~Do the drake-specific changes look good? (all commits after the merge commit)~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/57)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for review, please!

The review here should be relatively lightweight; no need to review upstream changes, just do a sanity check (see checkboxes in overview).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/57#-:-MqH5cEzDFTBLLPB2B6K:b-62aq04)* status: 0 of 177 files reviewed, all discussions resolved (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Sorry Eric -- I don't understand the instructions:
- "Does the commit title look correct?" There are 231 commits; to which one does this instruction refer?
- Correctness of "canary builds": I don't know what that means. CI is all green.
- Drake-specific changes (all after the merge commits): In the 2600-line Reviewable commit summary it appears that the last commit is a merge commit, with 11 files having merge conflicts: `- eea11ec: Merge remote-tracking branch 'upstream/master' into feature-update`. I don't know how to find the Drake-specific changes.

I would need something more like "instructions for dummies" to review this. Otherwise is there someone more knowledgeable who could review this with the current instructions?

> Reviewed 5 of 177 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/57#-:-MqHETNq79H_gjRovf2D:b-rmixi7)* status: 5 of 177 files reviewed, all discussions resolved (waiting on @sherm1)

**Comment by EricCousineau-TRI** [comment]
Sorry about that.

* I meant "PR title" - corrected that in the overview.
* Basically, compare the output of the "Python tests" section between base (see link) and this PR. Does this screenshot help indicate what you should compare? https://github.com/RobotLocomotion/pybind11/blob/drake/README_DRAKE.md#pulling-upstream-changes (basically, just check that we didn't have a huge drop in number of tests run)
* There aren't really any relevant Drake-specific changes; as mentioned above, all commits after merge commit, which there aren't any in this case. I've removed the bullet point in this case.

If this doesn't help illustrate / if you're still uncomfortable reviewing, I can also just self-stamp.

Thanks!

**Review by sherm1 — COMMENTED** [review]
OK, that helps -- thanks.
- I verified that the PR title commit is the last one in November (doesn't include a few December ones).
- I checked a few cases in CI and verified that lots of tests got run (~500).

So not much of a review, but FWIW :lgtm: !

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/57#-:-MqQ0CxW35JqOYlJjF1a:b-jsxhr6)* status: 5 of 177 files reviewed, all discussions resolved (waiting on @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 177 of 177 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

**Pull request merged**
