### PR TITLE
dtype object: Ensure fixed-size vectors are indexed correctly

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates RobotLocomotion/drake#9886

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/26)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/26#-:-LRc4DPcBqAEwc7wtD82:b-mchllo)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by EricCousineau-TRI** [comment]
All CI failures in TravisCI are due to this being an old fork, and are orthogonal to this PR.
Merging should not be blocked by those failures; instead, they should be addressed as part of
https://github.com/RobotLocomotion/drake/issues/10062.

**Comment by EricCousineau-TRI** [comment]
Since we have the fork update stuff merged in, CI should now pass; any failures should be a flag.

**Review by jamiesnape — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/26#-:-LRhpLR6BMH7XggbLVsh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
