### PR TITLE
Rebase onto `upstream/master` (`6d0b470`) from its previous upstream merge-base (`add56cc`)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This rebases our fork (currently at `14c31ad`) onto `upstream/master` (`e763f04`) from its previous upstream merge-base (`6d0b470`)

Process:
- [x] Merge old `drake` into `no_prune` with `merge --no-ff --strategy=ours`
- [x] Submit PR to Drake using this branch. Ensure experimental CI passes (including `mac-sierra` and `mac-highsierra`): https://github.com/RobotLocomotion/drake/pull/8860
- [x] Review this PR.
- [x] Reset `last_sha_of_previous_fork` to old `drake`, force push
- [x] Reset `upstream`, push without `--force`
- [x] Force push this branch onto `drake`
- ~Do NOT merge this PR.~ Merged via force push.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/18)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for review, please.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/18#-:-LDCXK0RCR3xYiViRxG6:b-lqtwh1)*

**Comment by EricCousineau-TRI** [comment]
Submitted a merge-compatible commit to prove that CI works. Once it passes, will revert to rebase.

**Comment by soonho-tri** [comment]
> Once it passes, will revert to rebase.

I think CI is happy. Could you revert it to rebase? I'll finish the review asap then.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/18#-:-LDHM8iFBdGU3szW2Oz2:bvuf9a5)*

**Comment by EricCousineau-TRI** [comment]
Done.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/18#-:-LDHOqyiD35t2CsIu1Qh:b-896fix)*

**Comment by soonho-tri** [comment]
:lgtm:

므ㅑ

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/18#-:-LDHY0o02_7NB1Nw0EC7:b4yfc4i)*

**Pull request merged**
