### PR TITLE
Merge 'upstream/v2.12.0'

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards https://github.com/RobotLocomotion/drake/issues/21577

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/71)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
Drake CI is passing. I assume this was just a vanilla merge with either no merge conflicts or trivially-fixed conflicts?  Then :lgtm:.

> Reviewed 87 of 87 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/71#-:-O-fTFaf6IzeZV62cjqr:b-vhqyk3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
> I assume this was just a vanilla merge with either no merge conflicts or trivially-fixed conflicts?

Yup. Main thing was merge conflicts for:
- Merging  v.2.12.0 into merge-base with v2.11.1 to - these have non-`main` commits for releases
- Merging `.github/workflows/ci.yml`, which is just ensuring things are commented out but still updated. Using VS Code's merge conflict editor is absolutely awesome for this.

**Comment by EricCousineau-TRI** [comment]
Working: Going to disable failing CI for the fork.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 70 of 87 files at r1, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/71)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Pull request merged**
