### PR TITLE
Merge `upstream/master` (35045ee) from previous merge-base (f2bd883)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Primarily for CI fixes

Process:
- [x] ~Submit PR to Drake using this branch. Ensure experimental CI passes~ Will be handled by #28
- [x] Review this PR.
- [x] Merge old `drake` into `no_prune` with `merge --no-ff --strategy=ours`
- [x] Reset `last_sha_of_previous_fork` to old `drake`, force push
- [x] Reset `upstream`, push without `--force`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/29)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@m-chaturvedi for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/29#-:-LeNS8Yn3bJ8ihpzth4r:btlv5xg)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @m-chaturvedi)

**Comment by m-chaturvedi** [comment]
:lgtm:

**Review by m-chaturvedi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/29)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @m-chaturvedi)

**Comment by EricCousineau-TRI** [comment]
Hm... Breathe seems to be struggling on CI. Will disable it for now.

**Pull request merged**
