### PR TITLE
eigen: Fix dtype=object shape conversion for 1D NumPy arrays for Eigen matrices

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
A step to fix RobotLocomotion#8620

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/16)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@soonho-tri Would you be able to review this, given that you are the platform reviewer for #8621?

**Comment by jwnimmer-tri** [comment]
Is this fix only applicable to new code we've added, not applicable to pybind11 master?

**Comment by EricCousineau-TRI** [comment]
Yup!

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/pybind11/16#-:-LANyF15EovwHiqvKsSo:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/pybind11/16#-:-LAO-b6QDsHTHljTxRfI:bnfp4nl)*

**Pull request merged**
