### PR TITLE
Skip Eigen::Sparse overloads when scipy is not available

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For https://github.com/RobotLocomotion/drake/pull/17570.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/59)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for review, please.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/59#-:-N7wyf4N1LBv05eyelih:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`include/pybind11/eigen.h` line 736 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/59#-N7wylMP-c0mSMURqEjt:-N7wylMP-c0mSMURqEju:b-jsf157) ([raw file](https://github.com/robotlocomotion/pybind11/blob/9b8c4ccd6a4e99fc3d65775249510f4db40ca9ec/include/pybind11/eigen.h#L736)):*
> ```objc
>         try {
>             sparse_module = module_::import("scipy.sparse");
>         } catch (const error_already_set &) {
> ```

BTW `error_already_set` feels a bit broad, but I can't think of anything better...

**Comment by jwnimmer-tri** [comment]
*[`include/pybind11/eigen.h` line 736 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/59#-N7wylMP-c0mSMURqEjt:-N7wzTbe7kXaBPnzkxMX:b-xo1ls4) ([raw file](https://github.com/robotlocomotion/pybind11/blob/9b8c4ccd6a4e99fc3d65775249510f4db40ca9ec/include/pybind11/eigen.h#L736)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `error_already_set` feels a bit broad, but I can't think of anything better...
</blockquote></details>

FYI That's the exact type that pybind11 throws:

https://github.com/RobotLocomotion/pybind11/blob/50c47be457b7663a96d5f1a7297ccc1453318829/include/pybind11/pybind11.h#L1067-L1070

The only other thing we could do would be to try to inspect the `err.matches(ImportError)` but that seemed like a lot of work.

**Comment by EricCousineau-TRI** [comment]
aye, makes sense - thanks for checking!

**Pull request merged**
