### PR TITLE
Merge 'upstream/master' (9c0aa69937)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Supersedes #46

WIP Branch: https://github.com/EricCousineau-TRI/pybind11/tree/feature-upstream-merge-wip

FYI @rwgk

---

EDIT: I (Eric) am going to just merge this as I see fit, because CI has gotten too messy.

For the author:

- [x] Ensure downstream CI passes (including Mac): https://github.com/RobotLocomotion/drake/pull/14225

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
~Reviewer checklist~:

See PR overview.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for basic review, please!

See checklist immediately above this:
https://github.com/RobotLocomotion/pybind11/pull/47#issuecomment-711430486

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MJxjqbgBpPiEDqo31dk:b-152oq1)* status: 0 of 172 files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47)* status: 0 of 172 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MJxkWOB0XL65Vhqzu9q:-MJxkWOB0XL65Vhqzu9r:b1y5akz) (no related file):*
Working:

Should ensure that downstream CI passes:
https://github.com/RobotLocomotion/drake/pull/14225

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
On the checklist:

1. It'd be good if you could be more specific on "the last few commits" as "the last *three* commits". It helps clarify in my mind what your intent/expectation is.
2. I'm a bit unsure on the third checklist. Other than acknowledging that you disabled a fair amount in e552063, I'm not too sure how to check that list.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK0JZfy5GpFC9lSOh6Z:b5nafm7)* status: 0 of 172 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
(1) Yes, the last three commits.
(2) Does the current CI coverage appear to cover what we have listed on Drake's supported configurations? (i.e. will it most likely help us capture any platform-specific errors before they strike us in Drake?)
https://drake.mit.edu/developers.html#supported-configurations

**Review by SeanCurtis-TRI — COMMENTED** [review]
As for (2), I was looking for guidance into this pybind fork. It doesn't look or smell like Drake CI configuration so the mapping is challenging. So, I don't need guidance as to links in Drake. I need guidance into understand how that relates to this fork.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK0_QvS0rcKHROfdfMM:b-tp361w)* status: 0 of 172 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
I guess to me your question is still a tad open-ended, so I don't know how to address it :P Will contact you for a VC.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd hoped it was simple:

> Do the new CI checks look correct? (Ubuntu, Mac, Python versions?)

In the thousands of changes included in this PR, how would I go about answering that question? Which files tell me that we've got the right mac versions? Ubuntu versions? Certainly, linking to drake CI indirectly provides a definition of "correct", but I'm still not sure how to take that ruler and use it to measure this fork. Remember, you're talking to someone who has never looked at this code before and Reviewable is *not* available for assessing this, as I have to asses commits individually.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK0gAuw2I4a8UQCqL7M:bdvspdy)* status: 0 of 172 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
Per VC:
- Should use GitHub, not Reviewable
- Indicate what commits (merge should be naive, functional should be separate)
- Will include instructions (as separate commit) about how to review fork-update PRs
 - Part of that will be what's the minimum canaries to review (e.g. bullet points, 2x2 with base vs. merge on Ubuntu & Mac CI)

**Comment by EricCousineau-TRI** [comment]
@SeanCurtis-TRI I've made the changes. I would love it if we can keep this descriptions as brief as possible; I also do not want to put the onus on me (or authors) to save you a few clicks on this PR for look at the PR's CI checks, since it will change each time there's a new push. (However, the author should def. show the base commit CI results)

Please take a look and see if this sufficient for now? We can always iterate later.

**Review by SeanCurtis-TRI — COMMENTED** [review]
So, if I understand correctly, you don't want to execute the very instructions that the most recent commit provides?

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK1qD6f31hj_U7TBdjp:b-7q2tkb)* status: 1 of 173 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I tried to follow the implied instructions from the README.

I used [this link](https://github.com/RobotLocomotion/pybind11/runs/1086934889?check_suite_focus=true#step:13:54) for ubuntu and [this link](https://github.com/RobotLocomotion/pybind11/runs/1086934867?check_suite_focus=true#step:13:54) for mac. However, when I examined the CI results for *this* PR, the [ubuntu results](https://github.com/RobotLocomotion/pybind11/runs/1277450212) and [mac results](https://github.com/RobotLocomotion/pybind11/runs/1277450174) seem to lack `Python tests C++17`, so no comparison is possible. So, that seems to be a CI failure.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK1rUhr0bd14jiWa5fQ:b-4q1jqx)* status: 1 of 173 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[README_DRAKE.md, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK1qq7u4VWOJ6dbTeoO:-MK1qq7vCzJJeZQatFvE:b-inm2t) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L167)):*
> ```Markdown
> following, exapnd `Python tests C++17`, and click on the the line number where
> `short test summary info` is printed:
> <https://github.com/RobotLocomotion/pybind11/actions?query=workflow%3ACI+branch%3Adrake+is%3Acompleted>
> ```

nit: Your instructions are one click short. When I follow the link provided here, it takes me to a page where I get this:



So, either your link does not do what you hope it would do, or you need to call out that *first* one clicks the "CI" link. Or some other, generally identifying trait.

**Comment by EricCousineau-TRI** [comment]
> So, if I understand correctly, you don't want to execute the very instructions that the most recent commit provides?

Ah, sorry; I had commented, then edited. I had added the checklist to the overview for this PR - did you have a chance to check that out? (sorry for not mentioning that)

> [...] seem to lack `Python tests C++17` [...]

:facepalm: Got changed. Will address that.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47)* status: 1 of 173 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[README_DRAKE.md, line 165 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK2RpCC-uUN9T5jb4wY:-MK2RpCD9B8v5B8NuTnB:b-yxprfk) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L165)):*
> ```Markdown
> 
> To get `<link>` for the given base CI results, use the latest result from the
> following, exapnd `Python tests C++17`, and click on the the line number where
> ```

nit spelling "expand"
___
*[README_DRAKE.md, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK1qq7u4VWOJ6dbTeoO:-MK2RdLDCVPdfoug4sC8:be9z0w8) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L167)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Your instructions are one click short. When I follow the link provided here, it takes me to a page where I get this:



So, either your link does not do what you hope it would do, or you need to call out that *first* one clicks the "CI" link. Or some other, generally identifying trait.
</blockquote></details>

Ah, I had tried to indicate that with "use the latest result from the following"; admittedly, that's a tad ambiguous.

What wording would you have preferred to say "look at the latest thing"?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I *had* missed that you'd edited the original listing. I've revisited the review from the provided links and the end result is the same as what I observed below -- CI is not building w.r.t. C++17.

> Reviewed 1 of 172 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MK5SlMj-XpxCyHA7lgl:bouvfo0)* status: 2 of 173 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[README_DRAKE.md, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK1qq7u4VWOJ6dbTeoO:-MK5TI6U2qkxkq3tOl9X:bqxftki) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L167)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, I had tried to indicate that with "use the latest result from the following"; admittedly, that's a tad ambiguous.

What wording would you have preferred to say "look at the latest thing"?
</blockquote></details>

I see what you were going for, but since both targets to be evaluated include the word "latest", I'd interpreted your use of the word, not as *new* information, but as a reference to the listed targets.

Perhaps  indicating that there may be multiple results, and the ubuntu-latest and mac-latest that should be checked are in the most *recent* result.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47)* status: 1 of 173 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[README_DRAKE.md, line 165 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK2RpCC-uUN9T5jb4wY:-MTbZjcD5TUzX4WxOVMe:b-896fix) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L165)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit spelling "expand"
</blockquote></details>

Done.
___
*[README_DRAKE.md, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MK1qq7u4VWOJ6dbTeoO:-MTbZYPd4R9EgckqtFc5:b-ja4lwd) ([raw file](https://github.com/robotlocomotion/pybind11/blob/c60b36852d08226c9d77b1b0726b9e1feaae5403/README_DRAKE.md#L167)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I see what you were going for, but since both targets to be evaluated include the word "latest", I'd interpreted your use of the word, not as *new* information, but as a reference to the listed targets.

Perhaps  indicating that there may be multiple results, and the ubuntu-latest and mac-latest that should be checked are in the most *recent* result.
</blockquote></details>

Done, I think. (Soz for delay)

The link has now expired, and I don't know how to ask GitHub Actions to keep results around forever.

Can we defer updating this til another PR? (base CI is now broken, due to my delay I believe)

**Comment by EricCousineau-TRI** [comment]
Hm... Given that this PR and master is now flat-out failing, I'm going to take executive power and just merge things myself in a separate PR.

@SeanCurtis-TRI Once I have baseline stuff working, I'll ensure that we can pick back up on the review.

**Review by EricCousineau-TRI — COMMENTED** [review]
-@seancurtis-tri per above text - I'm going to just make this work 'cause CI got messy

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MTbfmPQ5P2ThN2Bw505:b-ojrmad)* status: 1 of 193 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Self-stamp to avoid bitrot: +@ericcousineau-tri :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-:-MUz_j1i51uPi4bvY8Zi:b631g9z)* status: 1 of 196 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/47)* status: 1 of 196 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/47#-MJxkWOB0XL65Vhqzu9q:-MUzcbSI7iTuLGw_7WPK:b4qpzkh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working:

Should ensure that downstream CI passes:
https://github.com/RobotLocomotion/drake/pull/14225
</blockquote></details>

OK Manually tested downstream Drake on macsim. Was commit of Drake that uses pybind11 that didn't yet include multiple-inheritance fix, but meh:
https://github.com/RobotLocomotion/drake/commit/78b48149aadb6cef942aa7b340a3df3195295159

---

**Pull request merged**
