### PR TITLE
operators: Expose meta information

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
To more easily facilitate RobotLocomotion/drake#8389

Cherry-picked from #12

@soonho-tri Would you be OK with reviewing this?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/13)

### CODE REVIEW

**Comment by soonho-tri** [comment]
:lgtm:

The changes are seemingly harmless, but at the same time we do not utilize `info` in this PR, yet. But I guess we will do in the future PRs?  

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/pybind11/13#-:-L7jyL1NTa6nthto26CI:bz6irrh)*

**Comment by EricCousineau-TRI** [comment]
Yup, it's used in #12, and I'll use it now in #8389 (hopefully before this PR merges, so it can be validated upstream).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/pybind11/13#-:-L7jz50z0zkmS4L1-ybC:b-egwo55)*

**Comment by soonho-tri** [comment]
BTW, reviewable website allowed me to review this PR via its interface which is nice. But I guess it's not fully integrated yet as Github still asks me to provide a review.

Do you plan to enable reviewable workflow here?

**Review by soonho-tri — APPROVED** [review]

**Comment by soonho-tri** [comment]
>  I'll use it now in #8389

Nice!

**Comment by EricCousineau-TRI** [comment]
I'm a little tentative to do so (not sure how it will affect TravisCI), but can consider it.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/pybind11/13#-:-L7jzKOf8prUpStEbJGr:b-vvxgsa)*

**Comment by soonho-tri** [comment]
No rush. Just my wish.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/pybind11/13#-:-L7jzWBe5mIv2OKRuQ-f:b-pb777h)*

**Comment by EricCousineau-TRI** [comment]
Given that RobotLocomotion/drake#8389 did not even needs this, I'm going to go ahead close this PR.

**Pull request closed without merging**
