### PR TITLE
Update from upstream master (test_multiple_inheritance.cpp).

### PR DESCRIPTION
**Pull request by rwgk**
Importing https://github.com/pybind/pybind11/pull/2890.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/53)

### CODE REVIEW

**Comment by rwgk** [comment]
Hi @EricCousineau-TRI, the GitHub UI here won't let me assign a reviewer. How does it work here?

**Comment by EricCousineau-TRI** [comment]
Thanks Ralf!
Given that https://github.com/pybind/pybind11/pull/2890 is just some shuffling, is it OK if we hold off on this PR until there's a more substantial upstream update? (it requires some manual downstream testing on my part that I'd like to hold off on for now)

**Comment by rwgk** [comment]
Hi @EricCousineau-TRI, I looked into the drake-vs-smart_holder merge conflicts for pybind11.h. Currently there are 3 conflicts in pybind11.h, 2 are easy to resolve, but the one below looks like a show stopper, because you changed the interface of `init_instance`. I have SFINAE alternatives for the smart_holder code, which means your interface change will impact the smart_holder code one way or another (maybe it can be kept local to pybind11.h, I'm not sure). I see you also changed the interfaces of other functions from `const void *holder_ptr` to `detail::holder_erased holder_ptr`. Some of those are called from the smart_holder code, so those will be tricky to handle, too.

I will keep this PR open just in case you find it useful to have the resolved merge conflict for test_multiple_inheritance.cpp ready to copy over into your next drake-merge-master PR. Feel free to close this PR anytime.

```
<<<<<<< drake                                                                    
    static void init_instance(detail::instance *inst, detail::holder_erased holder_ptr) {
        using namespace detail;                                                 
=======                                                                         
    template <                                                                  
        typename T = type,                                                      
        detail::enable_if_t<!detail::type_uses_smart_holder_type_caster<T>::value, int> = 0>
    static void init_instance(detail::instance *inst, const void *holder_ptr) { 
>>>>>>> smart_holder                                                            
```

**Comment by EricCousineau-TRI** [comment]
Howdy Ralf! Sorry for delay here; this change will be incorporated in #57 (w/ merge conflicts), so I'll go ahead and close this PR.

Regarding the other merge conflicts, it's still on my plate to replace our smart ptr hacks w/ your better design, but just haven't gotten to it yet - thanks!

**Pull request closed without merging**
