### PR TITLE
Merge `upstream/master` (12e8774) from previous merge-base (35045ee)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Process:
- [x] Submit PR to Drake using this branch. Ensure experimental CI passes
- [x] Review this PR.
- [x] Merge old `drake` into `no_prune` with `merge --no-ff --strategy=ours`
- [x] Reset `last_sha_of_previous_fork` to old `drake`, force push
- [x] Reset `upstream`, push without `--force`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/31)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
CI errors due to bad stringification of exception, need to fix:
```
    def expect_ref_error(func):
        with pytest.raises(RuntimeError) as excinfo:
            func()
>       assert "dtype=object" in str(excinfo)
E       AssertionError: assert 'dtype=object' in '<ExceptionInfo RuntimeError tblen=2>'
E        +  where '<ExceptionInfo RuntimeError tblen=2>' = str(<ExceptionInfo RuntimeError tblen=2>)
test_eigen.py:207: AssertionError
```

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/31#-:-LnSeN_38xsk62T35PYS:b-mchllo)* status: 0 of 62 files reviewed, all discussions resolved (waiting on @jamiesnape)

**Review by jamiesnape — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/31#-:-LnSem2p4JoK1zroU3yK:bnfp4nl)* status: 0 of 62 files reviewed, all discussions resolved (waiting on @jamiesnape)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 62 of 62 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

**Pull request merged**
