### PR TITLE
Merge 'upstream/master' (76b7f53)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/67)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
@jwnimmer-tri I plan to YOLO merge this in too.
You OK with that?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/67#-:-NiFqnPc7wszVdMuOQ45:bkpg0n6)* status: 0 of 57 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
I saw your other question, and I'm still trying to decide what is best.

For sure we always want Drake's repository external to be pinned to the tip of this repo's `drake` branch.

The question is, would we prefer to keep this repo merged up only to stable upstream releases, or merged up to bleeding-edge commits?  I'm on the fence about that one.

I don't think CI here is relevant at all.  Drake CI is the only CI that matters.  So the question is really about do we want to ship (our patched version of) pybind11 upstream stable releases, or (our patch version of) pybind11 unstable master branch?

**Comment by jwnimmer-tri** [comment]
> So the question is really about do we want to ship (our patched version of) pybind11 upstream stable releases, or (our patch version of) pybind11 unstable master branch?

And for that, I'll defer to your best guess.  Generally I would lean to keeping with numbered releases (plus maybe some cherry-picks), but since we already have a bunch of local patches, possibly it's a moot point.

**Review by EricCousineau-TRI — COMMENTED** [review]
My preference for bleeding edge is really just to appease CI, and I see your point that this CI is maybe useful, but Drake CI is the one that matters.

I'm good w/ just merging in stable versions, and otherwise cherry pick what we need.

Will go ahead and close this out.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/67#-:-NiFwvRC2AqzYee0zLsl:bhcm7a3)* status: 0 of 57 files reviewed, all discussions resolved

**Comment by EricCousineau-TRI** [comment]
Closing this branch, pending release of stable version.

**Pull request closed without merging**
