### PR TITLE
Merge 'upstream/master' (8c0cd94) from previous merge-base (07e2259)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
`upstream/master`: https://github.com/pybind/pybind11/commit/8c0cd94465fbc1dbc34217e5a614edc784f0913e <- https://github.com/pybind/pybind11/commit/07e2259

Incorporates https://github.com/pybind/pybind11/releases/tag/v2.5.0

Process:
- [x] RobotLocomotion/drake#13579 Submit PR to Drake using this branch. Ensure experimental CI passes
- [x] Review this PR.

Follows format of #34

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for review please! (as platform reviewer on Tuesday)

Please review this in the same way that Jeremy did on prior PR:
https://github.com/RobotLocomotion/pybind11/pull/34#issuecomment-574689267

For full context, please review:
https://github.com/RobotLocomotion/pybind11/blob/drake/README_DRAKE.md#pulling-upstream-changes

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MANE4LAB-s3HNAsYiUj:b-2sbvim)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
This needs a feature review by someone who understands how this is supposed to work. I'm too far out of the loop to give this anything but a rubber stamp, which doesn't seem sufficient given the volume of changes. Maybe Jamie could provide an intelligent review? -@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MARolloC3wPkeAUfhRx:b-yujd24)* status: 0 of 40 files reviewed, all discussions resolved

**Comment by EricCousineau-TRI** [comment]
Sorry - what part of the instructions were unclear?
I would like to resolve this here, and I would like you to spend the time to be comfortable reviewing this change as platform reviewer.

I am happy to jump on a 10min VC with you to clarify the instructions.

**Comment by sherm1** [comment]
I read all the material you referenced and it made me think a feature review is required. For example, in Jeremy's instructions it said "make sure the commit has the right parent". I don't know whether it does or doesn't, but a feature reviewer would presumably know what that means.

**Comment by EricCousineau-TRI** [comment]
"the merge commit has the correct parents" is basically just saying that the commit title is accurate, and is truly merging into `robotlocomotion/drake` rather than `upstream/master`.

I don't think it's that feature-based, just checking for local Git commit consistency - sorry for not clarifying that!

Yeah, I don't really expect you to check off the files.
It's just a question of "is this PR title correct" and "does CI pass in this repo and in Drake".

Can I still ask for your review in this light, just to make sure I don't make any foolish git errors?

**Review by sherm1 — COMMENTED** [review]
OK, I'll take a crack at it on Tuesday. +@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MATTb1R3O6SOB_clTfl:b-oludv2)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @sherm1)

**Comment by EricCousineau-TRI** [comment]
Thanks!!!

**Review by rpoyner-tri — COMMENTED** [review]
@sherm1 feel free to flip this one to me if you'd prefer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MAWlgMsAWggPx6n3bo_:b-ttzlkh)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
OK, thanks -- +@rpoyner-tri for platform review, please.
(I'll take a final look.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MAWu7QOCBJ7gHpzL7lU:bog6y9o)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @rpoyner-tri and @sherm1)

**Review by rpoyner-tri — CHANGES_REQUESTED** [review]
Hashes and title are correct. Confirmed by pulling both fork, upstream, and PR branch locally and examining with good old `gitk`. Title checks out vs. provided instructions.
:lgtm: pending drake macOS CI evidence.

> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MAWxGOU3Xg4LbC6ES8O:b-oasayu)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-MAWy3uB9b9mtIR5rmfZ:-MAWy3uC1Zzsut7EAYYG:bqc7pp2) (no related file):*
Where do I find evidence of Drake macOS build happiness for this branch?

---

**Comment by sherm1** [comment]
All the CI evidence is in the companion PR https://github.com/RobotLocomotion/drake/pull/13579 which alleges to be using this same pybind11 update. Take a look there and see if you are convinced. It does have Mac CI.

**Review by sherm1 — APPROVED** [review]
Platform :lgtm: pending @rpoyner-tri's satisfaction with CI in the companion PR.

> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-:-MAX7xUl2XQuGqHwt8Sa:bcn2ho4)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/42#-MAWy3uB9b9mtIR5rmfZ:-MAX91cp-FVu1Cke8EpU:b-a7n6mc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Where do I find evidence of Drake macOS build happiness for this branch?
</blockquote></details>

Satisfied, per @sherm1 link to associated drake PR.

---

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
