### PR TITLE
class_: Register `reclaim_from_cpp` with constructing type

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards https://github.com/RobotLocomotion/drake/issues/13056

- [x] Test in downstream: https://github.com/robotlocomotion/drake/pull/13044

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/33)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
This came about because I was trying to bind `Simulator::release_context()`, but would get the following error:
```
Instance is registered but does not have a registered reclaim method. Internal error?
```

**Comment by EricCousineau-TRI** [comment]
FTR, debugging in a prior push was helpful for me. I will try to upstream some utilities / suggestions.
Specifically, commit 09a1b0c8 (focus CI) and 87dd63a6 (drilling in to debug).

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for review, please?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/33#-:-M4uhVbF-Zg-_NlIxqGK:b-89l98f)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sammy-tri)

**Review by sammy-tri — APPROVED** [review]
I think I understand at a surface level what's going on from the test and the linked PR, but I'm not going to claim I understand what's going on in the pybind11 internals.  If it solves your problem, :lgtm:.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/33#-:-M4unSK2EQNEy5OYrC5o:b-x2l9in)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by EricCousineau-TRI** [comment]
Thanks!

**Pull request merged**
