### PR TITLE
Merge 'upstream/master' (v2.11.1, 8a099e44b)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Coarse notes on how merges were attempted:
https://github.com/EricCousineau-TRI/repro/blob/d476556c8d273b9a26f23adf3bbba798b317578b/drake_stuff/pybind_update_2023/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/64)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/64)* status: 0 of 217 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/pybind11/64#-NgzYg8W03C7av8_3FFq:-NgzYg8W03C7av8_3FFr:b-gpfcr0) (no related file):*
Bumping the version is good.  For Drake review, we don't need to review the patches pulled in from upstream but we _do_ need to review anything manually that you did -- merge conflicts, bug fixes, additional adjustments, etc.

How do I obtain the inventory of those diff(s) to start my review?

___

**Comment by EricCousineau-TRI** [comment]
I had done multiple merges. I am not sure if this is the best way, but I can see my PR commits as so:
```
gitk --first-parent robotlocomotion/drake..HEAD
```

For most merge commits, the resolutions can be seen as bold black, with the separate parents shown in red and blue (see image below)

However, gitk seems to be unable to show conflict resolutions for certain merges (f5a414c291, 098786d562e).
It could be that I used "unorthodox" ways to resolve the conflicts - I had tried to merge a few times, and had to replay. In some cases, I may have ruined them by using something like
```
git reset HEAD; git checkout --no-overlay <other-commit-with-resolved-worktree> -- :/
```
(I was hoping git would "just figure out" the conflicts magically based on the staged worktree at the end)

Is this at all useful, or should I approach this in a different way?

---

`gitk` example
> image

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/pybind11/64)* status: 0 of 217 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/pybind11/64#-NgzYg8W03C7av8_3FFq:-Nh7tZpc6j37KiKRhPnT:bnxn8wt) (no related file):*
> Is this at all useful, or should I approach this in a different way?

I'll give it a try.

___

**Comment by jwnimmer-tri** [comment]
This is completely impossible to review.  I tried looking at the merge commits, but they keep overwriting each other.  So then I tried comparing the drake-specific overall diff beween this PR and v2.11 to the head of RL/pybind11 drake branch with its upstream merge base, and that's impossible too.

So our only options are to YOLO it, or to never touch it again (throw it all away).

It seems like you're on the YOLO train, so I guess we can do that.  Hopefully you will be on deck to fix any bug reports that arise from this upgrade.

:lgtm: rubber stamp.

**Comment by jwnimmer-tri** [comment]
In case I wasn't clear, I think we might as well just merge this and move on.

**Comment by EricCousineau-TRI** [comment]
aye, YOLO works for me!

**Pull request merged**
