### PR TITLE
Merge 'upstream/master' (1caf1d06)

### LINKED ISSUE #13800: pybind11: Should upgrade to use GitHub actions CI
pybind11's CI switched to GitHub actions (and looks wayyy better).

However, I don't want to have that be part of an upstream merge PR (for #13792)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves https://github.com/RobotLocomotion/drake/issues/13800

Process:
- [x] RobotLocomotion/drake#14028 Submit PR to Drake using this branch. Ensure experimental CI passes
- [x] Review this PR - review will only consist of checking the minor Drake-specific modifications

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/43)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/43)* status: 0 of 127 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/43#-MDmeKky8JWLkZNOH4wQ:-MDmeKky8JWLkZNOH4wR:bcvhrd4) (no related file):*
Working: I have no idea how to test out transitioning for GitHub actions, so meh for now.
Filed: https://github.com/RobotLocomotion/drake/issues/13800

---

**Comment by EricCousineau-TRI** [comment]
~This is a can o' worms. Going to cherry-pick route.~

EDIT: Updated.

**Comment by EricCousineau-TRI** [comment]
Reviewer checklist:
- [x] Does the commit title look correct? (does it only contain up to 1caf1d06 of upstream?)
- [x] Do the drake-specific changes (the last few commits) look OK? (no windows, no PyPy, no Python 2.7 / 3.5)
- [x] Do the new CI checks look correct? (Ubuntu, Mac, Python versions?)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for review, please. Please see the reviewer checklist in this PR (no need to review the upstream code itself):
https://github.com/RobotLocomotion/pybind11/pull/43#issuecomment-687840181

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/43#-:-MGaP1an6O2un2IDVu7Y:b-d87j3c)* status: 0 of 129 files reviewed, all discussions resolved (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/43#-MDmeKky8JWLkZNOH4wQ:-MGaOaW8A6BV5G7iren6:b65nzq6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I have no idea how to test out transitioning for GitHub actions, so meh for now.
Filed: https://github.com/RobotLocomotion/drake/issues/13800
</blockquote></details>

OK Done.

I just pushed a change to `robotlocomotion/drake` that enabled a placeholder GitHub Actions config which allows actions to run on PRs (which will have modified actions):
https://github.com/RobotLocomotion/pybind11/blob/8bc3aa1011819e61bc8a77aae2e45167bd3bff82/.github/workflows/ci.yml

---

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 122 of 127 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/43#-:-MGiUW9w9aGNdHkqoTvW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
