### PR TITLE
Throw TypeError when subclasses forget to call __init__

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Cherry-pick of https://github.com/pybind/pybind11/pull/2152

(Trying to do a full update in #43 was a bit too painful)

- [ ] https://github.com/RobotLocomotion/drake/pull/13801 Submit PR to Drake using this branch. Ensure experimental CI passes
- [ ] Review this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/44)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/44#-:-MDmjp6I43d-anP0ySQG:bncztub)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @RussTedrake)

**Review by RussTedrake — APPROVED** [review]
:LGTM:  class.h looks like a foreign language to me, but it’s from upstream, and the tests they add are clearly what I was hoping for.  Thanks!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/44#-:-MDnm0lk6lhKkx5tdc7k:b-4389up)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RussTedrake — APPROVED** [review]
(but it looks like travis CI is not happy)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/44#-:-MDnmFSk7OEc4-OHvVYk:b-99cinp)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by EricCousineau-TRI** [comment]
I believe all failures are irrelevant here. From: https://travis-ci.com/github/RobotLocomotion/pybind11/builds/178206816
* 221.10: Bad provisioning
* 221.12: CPython 3.9 is still in beta
* 221.13: PyPy 2.7 - two things we don't care about (PyPy CPython, 2.7 vs 3.x)
* 221.14: PyPy 3.6 - also do not care about this one.

Merging!

CI itself should be made more stable once https://github.com/RobotLocomotion/drake/issues/13800 is resolvedd

**Pull request merged**
