### PR TITLE
Improve Python 3.11 support

### PR DESCRIPTION
**Pull request by svenevs**
Backport of https://github.com/pybind/pybind11/pull/3694

Relates: https://github.com/RobotLocomotion/drake/pull/18262, https://github.com/RobotLocomotion/drake/pull/18297

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/60)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
CC @jwnimmer-tri for review please (I don't have perms to assign on this repo).  Drake PR that ran CI against this: https://github.com/RobotLocomotion/drake/pull/18262

Specifically:

- Existing [linux wheel works as expected](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/95/console) (test patch doesn't break prior python)
- mac arm [wheel build with 3.11 works](https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release/10/console)
- mac x86_64 [wheel build with 3.11 works](https://drake-jenkins.csail.mit.edu/job/mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release/2/console)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/60#-:-NGXeDfJ2WrVWDnBMKuc:b50lazz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
Please open a Drake PR that has the sha bump for pybind11 to this PR, and launch a full CI run there (in particular, with 3.10 still on macOS).

**Review by jwnimmer-tri — APPROVED** [review]
LGTM pending Drake CI.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/60#-:-NGXkShTDD3SCriJer8e:b-z6m7zv)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/60#-NGXkFlV5uzRb3UAdrS5):*
nit To my first reading, you didn't need to adjust the patch at all, you took it straight as-is with no merge conflicts.  If so, that's a cherry-pick, not a backport.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/60)* status: all files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/pybind11/60#-NGXnRbs-7RFJA8FMuBA:-NGXnRbs-7RFJA8FMuBB:b6w9zb0) (no related file):*
Working,

> Please open a Drake PR that has the sha bump for pybind11 to this PR, and launch a full CI run there (in particular, with 3.10 still on macOS).

=> https://github.com/RobotLocomotion/drake/pull/18297

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/pybind11/60#-NGXkFlV5uzRb3UAdrS5):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit To my first reading, you didn't need to adjust the patch at all, you took it straight as-is with no merge conflicts.  If so, that's a cherry-pick, not a backport.
</blockquote></details>

The patch does not apply, there seems to have been a `clang-format` and/or style convention change.  It was manually backported.

**Review by jwnimmer-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/pybind11/60)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

**Pull request merged**
